### ISSUE TITLE
数据预处理错误

### ISSUE THREAD

**Issue by Shaker-Chen** [Noah0115/boss_drf#2]
点击数据预处理显示：出错了: Internal Server Error

**Comment by Noah0115** [comment]
你好 提供一下具体报错信息

**Comment by Shaker-Chen** [comment]
Internal Server Error: /data_init/
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\asgiref\sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\asgiref\sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
  File "G:\Code\Python\boss_drf\back\api\index.py", line 54, in data_init
    is_success = run()
  File "G:\Code\Python\boss_drf\back\utils\data_init.py", line 267, in run
    count_word()
  File "G:\Code\Python\boss_drf\back\utils\data_init.py", line 202, in count_word
    fieldnames.to_csv('weights/' + job_name + '.csv', index=False)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\util\_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\generic.py", line 3961, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\io\formats\format.py", line 1014, in to_csv
    csv_formatter.save()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\io\formats\csvs.py", line 251, in save
    with get_handle(
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\io\common.py", line 749, in get_handle
    check_parent_directory(str(handle))
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\io\common.py", line 616, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: 'weights'
HTTP GET /data_init/ 500 [0.62, 127.0.0.1:53042]

**Comment by Noah0115** [comment]
OSError: Cannot save file into a non-existent directory: 'weights'
手动在utils下创建weights文件夹

**Comment by Shaker-Chen** [comment]
Internal Server Error: /data_init/
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\asgiref\sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\asgiref\sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
  File "G:\Code\Python\boss_drf\back\api\index.py", line 54, in data_init
    is_success = run()
  File "G:\Code\Python\boss_drf\back\utils\data_init.py", line 267, in run
    count_word()
  File "G:\Code\Python\boss_drf\back\utils\data_init.py", line 192, in count_word
    x = (sd[i][1] / job_count[job_name]) * (sd[i][1] / all_skill[i][1])
KeyError: nan
HTTP GET /data_init/ 500 [0.71, 127.0.0.1:54198]

**Comment by Noah0115** [comment]
我这边测试是没问题的，根据项目README，检查一下环境配置是否正确。
